Metrics/BlockLength:
  Max: 200

Metrics/MethodLength:
  Max: 100

Metrics/AbcSize:
  Max: 100

Layout/LineLength:
  Max: 200 

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15 
